language: php
sudo: false

php:
  - 7.1
  - hhvm

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
  - if [[ $TRAVIS_PHP_VERSION != '5.6' && $TRAVIS_PHP_VERSION != 'hhvm' ]]; then phpenv config-rm xdebug.ini; fi
  - travis_retry composer self-update
  - travis_retry composer update $COMPOSER_FLAGS

script: vendor/bin/phpunit $PHPUNIT_FLAGS
