language: php
sudo: false

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
  - if [[ $TRAVIS_PHP_VERSION = '5.6' ]]; then echo "xdebug.max_nesting_level=1000" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - if [[ $TRAVIS_PHP_VERSION = '5.6' ]]; then PHPUNIT_FLAGS="--coverage-clover=coverage.clover"; else PHPUNIT_FLAGS=""; fi
  - if [[ $TRAVIS_PHP_VERSION != '5.6' && $TRAVIS_PHP_VERSION != 'hhvm' ]]; then phpenv config-rm xdebug.ini; fi
  - travis_retry composer self-update
  - travis_retry composer update $COMPOSER_FLAGS

script: vendor/bin/phpunit $PHPUNIT_FLAGS
